### ISSUE TITLE
ImportError: cannot import name 'base' from 'sqlalchemy.ext.declarative'

### ISSUE THREAD

**Issue by thomaxxl** [valhuber/LogicBank#5] opened 2021-10-01 07:47 UTC
Hi,

I get this error with `SQLAlchemy==1.4.25`:
`ImportError: cannot import name 'base' from 'sqlalchemy.ext.declarative'`

This does work for `SQLAlchemy==1.3.20`

**Comment by valhuber** [comment] 2021-10-01 08:15
This happened running the docker or pip version?  Did you make changes first?  What did you do to see this?

Thanks,
Val

**Comment by thomaxxl** [comment] 2021-10-01 08:24
```
mkdir venv
virtualenv -p python3.9 venv/
source venv/bin/activate
pip install logicbank

(venv) /var/tmp $ python
Python 3.9.5 (default, May 19 2021, 11:32:47)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from logic_bank.logic_bank import LogicBank, Rule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/automat/C2/C2_server/LogicBank/logic_bank/logic_bank.py", line 6, in <module>
    from logic_bank.rule_bank import rule_bank_withdraw  # reduce circular imports
  File "/home/automat/C2/C2_server/LogicBank/logic_bank/rule_bank/rule_bank_withdraw.py", line 6, in <module>
    from logic_bank.exec_row_logic.logic_row import LogicRow
  File "/home/automat/C2/C2_server/LogicBank/logic_bank/exec_row_logic/logic_row.py", line 5, in <module>
    from sqlalchemy.ext.declarative import base
ImportError: cannot import name 'base' from 'sqlalchemy.ext.declarative' (/var/tmp/venv/lib/python3.9/site-packages/sqlalchemy/ext/declarative/__init__.py)
>>>
```

**Comment by thomaxxl** [comment] 2021-10-01 08:29
```
mkdir venv
virtualenv -p python3.9 venv/
source venv/bin/activate
pip install logicbank
```

```
automat@automat-c2:~ $ mkdir /tmp/t
automat@automat-c2:~ $ cd !$
cd /tmp/t
automat@automat-c2:t $ mkdir venv
automat@automat-c2:t $ virtualenv -p python3.9 venv/
created virtual environment CPython3.9.5.final.0-64 in 310ms
  creator CPython3Posix(dest=/tmp/t/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/home/automat/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
automat@automat-c2:t $ source venv/bin/activate
(venv) automat@automat-c2:t $ pip install logicbank
Collecting logicbank
  Downloading logicbank-1.0.2-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.8 MB/s
Collecting python-dateutil<3,>=2.3
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 18.3 MB/s
Collecting sqlalchemy-utils<1,>=0.32.21
  Downloading SQLAlchemy_Utils-0.37.8-py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 13.4 MB/s
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting SQLAlchemy>=1.0
  Downloading SQLAlchemy-1.4.25-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 22.1 MB/s
Collecting greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))))
  Downloading greenlet-1.1.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (153 kB)
     |████████████████████████████████| 153 kB 61.4 MB/s
Installing collected packages: six, python-dateutil, greenlet, SQLAlchemy, sqlalchemy-utils, logicbank
Successfully installed SQLAlchemy-1.4.25 greenlet-1.1.2 logicbank-1.0.2 python-dateutil-2.8.2 six-1.16.0 sqlalchemy-utils-0.37.8
(venv) automat@automat-c2:t $ python
Python 3.9.5 (default, May 19 2021, 11:32:47)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from logic_bank.logic_bank import LogicBank, Rule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/t/venv/lib/python3.9/site-packages/logic_bank/logic_bank.py", line 6, in <module>
    from logic_bank.rule_bank import rule_bank_withdraw  # reduce circular imports
  File "/tmp/t/venv/lib/python3.9/site-packages/logic_bank/rule_bank/rule_bank_withdraw.py", line 6, in <module>
    from logic_bank.exec_row_logic.logic_row import LogicRow
  File "/tmp/t/venv/lib/python3.9/site-packages/logic_bank/exec_row_logic/logic_row.py", line 5, in <module>
    from sqlalchemy.ext.declarative import base
ImportError: cannot import name 'base' from 'sqlalchemy.ext.declarative' (/tmp/t/venv/lib/python3.9/site-packages/sqlalchemy/ext/declarative/__init__.py)
>>>
(venv) automat@automat-c2:t $ pip freeze
greenlet==1.1.2
logicbank==1.0.2
python-dateutil==2.8.2
six==1.16.0
SQLAlchemy==1.4.25
SQLAlchemy-Utils==0.37.8
```

**Comment by valhuber** [comment] 2021-10-01 10:09
Sqlalchemy 1.4 changed its API, so is not compstible. I do have a branch for that, but cannot use it because flask app builder is not upgraded,  so we are stuck at 1.3.x until he upgrades.

My requirents files do say 1.3.  How did you wind up with 1.4?

Thanks,
Val

**Comment by thomaxxl** [comment] 2021-10-01 10:35
I didn't specify a version, as you can see/reproduce from the console output.

**Comment by valhuber** [comment] 2021-10-01 13:42
OK, I can reproduce, as shown below.

Not sure why it's loading SQLAlchemy 1.4 -- here is `requirements.txt` for logicbank:

```
python-dateutil==2.8.1
six==1.15.0
SQLAlchemy==1.3.23
# SQLAlchemy-Utils==0.36.8
LogicBankUtils
```

Perhaps I need to put SQLAlchemy _before_ six?

```
val@Vals-MacBook-Pro-16 ~ % cd /Users/val/Desktop/test 
val@Vals-MacBook-Pro-16 test % virtualenv venv         
created virtual environment CPython3.9.1.final.0-64 in 576ms
  creator CPython3Posix(dest=/Users/val/Desktop/test/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/val/Library/Application Support/virtualenv)
    added seed packages: pip==21.2.4, setuptools==58.0.4, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
val@Vals-MacBook-Pro-16 test % source venv/bin/activate
(venv) val@Vals-MacBook-Pro-16 test % pip install logicbank
Collecting logicbank
  Using cached logicbank-1.0.2-py3-none-any.whl (42 kB)
Collecting sqlalchemy-utils<1,>=0.32.21
  Using cached SQLAlchemy_Utils-0.37.8-py3-none-any.whl (100 kB)
Collecting python-dateutil<3,>=2.3
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting SQLAlchemy>=1.0
  Downloading SQLAlchemy-1.4.25-cp39-cp39-macosx_10_14_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 3.5 MB/s 
Collecting greenlet!=0.4.17
  Downloading greenlet-1.1.2-cp39-cp39-macosx_10_14_x86_64.whl (92 kB)
     |████████████████████████████████| 92 kB 2.5 MB/s 
Installing collected packages: greenlet, SQLAlchemy, six, sqlalchemy-utils, python-dateutil, logicbank
Successfully installed SQLAlchemy-1.4.25 greenlet-1.1.2 logicbank-1.0.2 python-dateutil-2.8.2 six-1.16.0 sqlalchemy-utils-0.37.8
(venv) val@Vals-MacBook-Pro-16 test % 
```

**Comment by valhuber** [comment] 2021-10-01 14:08
Hmm, appears that ordering the `requirements.txt` does not help...

I have uploaded an experimental LogicBank with the following requirements:
```
SQLAlchemy==1.3.24
python-dateutil==2.8.1
six==1.15.0
LogicBankUtils
````

But, it still is picking the wrong SQLAlchemy out of cache:
```
(venv) val@Vals-MacBook-Pro-16 test % pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple logicbank==1.0.3
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Collecting logicbank==1.0.3
  Downloading https://test-files.pythonhosted.org/packages/3c/37/2c0b4d55f9a5eda4016572743a171e734815faac26662a67f1eefb10aabd/logicbank-1.0.3-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 615 kB/s 
Collecting sqlalchemy-utils<1,>=0.32.21
  Using cached SQLAlchemy_Utils-0.37.8-py3-none-any.whl (100 kB)
Collecting python-dateutil<3,>=2.3
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting SQLAlchemy>=1.0
  Using cached SQLAlchemy-1.4.25-cp39-cp39-macosx_10_14_x86_64.whl (1.5 MB)
Collecting greenlet!=0.4.17
  Using cached greenlet-1.1.2-cp39-cp39-macosx_10_14_x86_64.whl (92 kB)
Installing collected packages: greenlet, SQLAlchemy, six, sqlalchemy-utils, python-dateutil, logicbank
Successfully installed SQLAlchemy-1.4.25 greenlet-1.1.2 logicbank-1.0.3 python-dateutil-2.8.2 six-1.16.0 sqlalchemy-utils-0.37.8
(venv) val@Vals-MacBook-Pro-16 test % 
```

**Comment by valhuber** [comment] 2021-10-01 14:49
fixed in just-released https://pypi.org/project/logicbank/1.0.5/

**Closed as completed by valhuber** 2021-10-01 14:49 UTC
